language: node_js

sudo: false

before_install:
- '[ "${TRAVIS_PULL_REQUEST}" == "false" ] && openssl aes-256-cbc -K $encrypted_cb7060b3a42b_key -iv $encrypted_cb7060b3a42b_iv -in transit-gateway.env.enc -out transit-gateway.env -d || true'
- '[ "${TRAVIS_PULL_REQUEST}" == "false" ] && openssl aes-256-cbc -K $encrypted_6de0fb2f002f_key -iv $encrypted_6de0fb2f002f_iv -in directlink.env.enc -out directlink.env -d || true'

jobs:
  include:
    - stage: Node JS 10
      node_js: 10
    - stage: Node JS 12
      node_js: 12

script:
- npm run build
- npm run test-travis || travis_terminate 1
- npm run lint
- npm run check-packages
# - sh scripts/typedoc/generate_typedoc.sh

after_success:
- npm run report-coverage
# - scripts/jsdoc/publish.sh - currently in progress

# To enable semantic-release, uncomment this section.
deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 12
    branch: master
