dist: jammy

language: node_js

sudo: false

node_js:
- 20
- 22

before_install:
- '[ "${TRAVIS_PULL_REQUEST}" == "false" ] && openssl aes-256-cbc -K $encrypted_3d8a3eb98382_key -iv $encrypted_3d8a3eb98382_iv -in transit.env.enc -out transit.env -d || true'
- '[ "${TRAVIS_PULL_REQUEST}" == "false" ] && openssl aes-256-cbc -K $encrypted_6de0fb2f002f_key -iv $encrypted_6de0fb2f002f_iv -in directlink.env.enc -out directlink.env -d || true'
- '[ "${TRAVIS_PULL_REQUEST}" == "false" ] && openssl aes-256-cbc -K $encrypted_fc092b9428d6_key -iv $encrypted_fc092b9428d6_iv -in cis.env.enc -out cis.env -d || true'
- '[ "${TRAVIS_PULL_REQUEST}" == "false" ] && openssl aes-256-cbc -K $encrypted_fb1b85a9795b_key -iv $encrypted_fb1b85a9795b_iv -in cislog.env.enc -out cislog.env -d || true'
- '[ "${TRAVIS_PULL_REQUEST}" == "false" ] && openssl aes-256-cbc -K $encrypted_89a9eb4f9417_key -iv $encrypted_89a9eb4f9417_iv -in dns.env.enc -out dns.env -d || true'

script:
- npm run build
# - travis_wait 30 npm run test-travis || travis_terminate 1
- npm run test-unit-travis || travis_terminate 1
# - npm run lint
- npm run check-packages
# - sh scripts/typedoc/generate_typedoc.sh

deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 22
    branch: master